### ISSUE TITLE
`Docker-compose`를 이용한 서비스 클러스터 구성

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#107]
**Problem or enhancements and It's Background**
- 현재 `Honeypots-Core` 서버 애플리케이션은 여러 관련 애플리케이션과 함께 동작한다.
  - `H2 Database`
  - `Prometheus`
  - `Grafana`
- 이러한 애플리케이션간의 호환성을 안정적으로 보장하고 서비스 배포를 용이하게 하기 위해 `Docker-compose`를 이용해 서비스 클러스터를 구성하도록 하자.

**Solutions**
- `Docker-compose`를 이용한 서비스 클러스터 구성

**TODO Tasks**
- [x] `Docker-compose` 설정파일 작성
- [x] `Honeypots-Core` App 이미지 생성 위한 `Dockerfile` 스크립트 작성
- [x] Gradle `distribution` 플러그인 추가 및 배포본 패키징 위한 스크립트 작성
- [x] `Prometheus` 모니터링 target 주소 docker internal host로 변경
