### ISSUE TITLE
KPI조회를 위한 API 설계 및 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#112]
**Problem or enhancements and It's Background**
- MVP 단계의 프로젝트의 최종 발표를 위해 몇 가지 성과지표 추출이 필요하다.
  - `User Engagement` : 전체 회원수, 게시글 수, 댓글 수, 좋아요 수
  - `Active User` : 일간 활성 사용자 수 (DAU)
  - 신규 회원 수 추이
- 위 지표들을 Admin dashboard에서 조회할 수 있도록 API를 개발하도록 하자.

**Solutions**
- KPI 조회 API 개발

**TODO Tasks**
- [x] `User Engagement` : 전체 회원수, 게시글 수, 댓글 수, 좋아요 수 조회 API 개발
- [x] `Active User` : 일간 활성 사용자 수 (DAU) 조회 API 개발
- [x] 신규 회원 수 추이 조회 API 개발
- [x] Admin dashboard에서 API 접근 가능하도록 CORS 허용
