### ISSUE TITLE
Push 메시지 전송 내역 (알림 내역) 저장 및 API 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#127]
**Problem or enhancements and It's Background**
- 현재 알림 권한을 허용한 사용자에게는 Push 알림이 전송되어 사용자간 상호작용 증대 및 앱 참여율 향상을 기대할 수 있다.
- 그러나 알림 권한을 허용하지 않은 사용자는 앱 사용에 대한 피드백 (댓글, 리액션 등)을 직접 확인하여야 한다.
- 알림 내역을 조회할 수 있도록 하여 알림 권한을 허용하지 않은 사용자에게도 알림 내용을 제공할 수 있도록 하자.

**Solutions**
- 알림 내역 저장 및 API 개발

**TODO Tasks**
- [x] 알림 내역 저장할 Table, Entity 설계
- [x] 알림 내역 조회 API 개발
- [x] `Notification Event Trigger Point`에서 알림 내역 저장
