### ISSUE TITLE
H2 DB 및 JPA 환경 설정

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#2]
**Problem or enhancements and It's Background**
- 프로젝트에 사용될 ORM 기술인 JPA의 초기 환경 설정이 필요
- Datasource로 H2 DB를 이용하며, 개발/운영 환경을 구분하여 설정 필요

**Solutions**
- JPA 사용을 위해 Datasource로 H2를 추가하고 초기 설정값 세팅하기

**TODO Tasks**
- [x] Spring jdbc, Spring JPA, H2 의존성 추가
- [x] 환경별 H2 모드 설정 (prod: tcp mode, dev: in-memory mode)
- [x] 환경별 JPA ddl-auto 설정 (prod: update, dev: create)
