### ISSUE TITLE
사용자 인증 로직 분리하기

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#28]
**Problem or enhancements and It's Background**
- 현재 사용자 인증을 위해 전송받은 `Authorization` 헤더의 `token`값을 각 Handler method에서 반복적으로 처리하고 있다.
- Servlet Filter 또는 interceptor를 이용하여 토큰 검증 및 사용자 정보 획득 로직의 중복을 제거하도록 하자.

**Solutions**
- 사용자 인증을 수행하는 Servlet Filter 또는 interceptor 구성하기

**TODO Tasks**
- [x] 사용자 인증 Filter 또는 interceptor 구성
- [x] 사용자 인증이 필요한 endpoints와 필요하지 않은 endpoints 구분하여 필터링
- [x] `Spring security` 적용하기
