### ISSUE TITLE
중고거래 게시글 관련 API 설계 및 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#42]
**Problem or enhancements and It's Background**
- 사용자간 중고거래 커뮤니티를 형성을 위해 중고거래 게시글관련 API를 설계 및 개발하자.
- 일반 게시글 조회/작성/수정/삭제와 큰 틀에서는 비슷하지만 거래 상태, 거래 금액, 대화를 위한 링크 등의 내용이 추가된다.
- 또한, 이미지 업로드도 가능해야 한다.

**Solutions**
- 중고거래 게시글 CRUD API 설계 및 개발

**TODO Tasks**
- [x] S3 버킷 내, 중고거래 게시글에 첨부된 이미지 파일 저장할 폴더 구성
- [x] CRUD API 설계 및 개발
- [x] API 문서 업데이트
