### ISSUE TITLE
마이페이지 관련 API 설계 및 개발

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#56]
**Problem or enhancements and It's Background**
- 마이페이지 내 `나의 활동` 메뉴를 위한 API가 필요하다.
  - 내가 작성한 게시글
  - 내가 작성한 중고거래 게시글
  - 내가 작성한 공동구매 게시글

**Solutions**
- 회원별, 게시글 유형별 게시글 목록 조회 API 설계 및 개발

**TODO Tasks**
- [x] 회원별 일반 게시글 조회 API 개발
- [x] 회원별 중고거래 게시글 조회 API 개발
- [x] 회원별 공동구매 게시글 조회 API 개발
- [x] Factory Pattern을 이용한 서비스 구현체 이용할 수 있도록 하기
