### ISSUE TITLE
게시판 관련 엔티티 및 테이블 설계

### ISSUE THREAD

**Issue by Dokyeongyun** [HoneyPots/HoneyPots-Core#8]
**Problem or enhancements and It's Background**
- 게시판 관련된 기능의 구현을 위해 엔티티 및 테이블의 설계 필요
    - 게시글
        - 일반 게시판 
        - 중고거래 게시판
        - 공동구매 게시판
    - 댓글
    - 게시글 및 댓글 리액션

**Solutions**
- JPA를 이용한 게시판 관련 엔티티 및 테이블 설계

**TODO Tasks**
- [x] 게시판별 테이블 설계
- [x] 댓글 테이블 설계
- [x] 게시글 및 댓글 리액션 테이블 설계
